services:
  tarrow-test-db:
    image: postgres:14
    ports:
      - "35431:5432"
    environment:
      POSTGRES_USER: tarrow-dev
      POSTGRES_PASSWORD: tarrow-dev
      POSTGRES_DB: tarrow-test-db

